version: '3.8'
services:

  db_5436:
    image: postgres:17-alpine
    container_name: phoenix_chat_app_db_5436
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chat_app_test
    ports:
      - "5436:5432"
    volumes:
      - postgres_5436_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_5436_data: