# This file is automatically generated by ExAws.
# Do not edit this file manually.

%{
  "partitions" => [
    %{
      "defaults" => %{
        "hostname" => "{service}.{region}.{dnsSuffix}",
        "protocols" => ["https"],
        "signatureVersions" => ["v4"]
      },
      "dnsSuffix" => "amazonaws.com",
      "partition" => "aws",
      "partitionName" => "AWS Standard",
      "regionRegex" => "^(us|eu|af|ap|sa|ca|me)\\-\\w+\\-\\d+$",
      "regions" => %{
        "af-south-1" => %{"description" => "Africa (Cape Town)"},
        "ap-northeast-1" => %{"description" => "Asia Pacific (Tokyo)"},
        "ap-northeast-2" => %{"description" => "Asia Pacific (Seoul)"},
        "ap-east-1" => %{"description" => "Asia Pacific (Hong Kong)"},
        "ap-south-1" => %{"description" => "Asia Pacific (Mumbai)"},
        "ap-south-2" => %{"description" => "Asia Pacific (Hyderabad)"},
        "ap-southeast-1" => %{"description" => "Asia Pacific (Singapore)"},
        "ap-southeast-2" => %{"description" => "Asia Pacific (Sydney)"},
        "ap-southeast-3" => %{"description" => "Asia Pacific (Jakarta)"},
        "ca-central-1" => %{"description" => "Canada (Montreal)"},
        "ca-west-1" => %{"description" => "Canada (Calgary)"},
        "eu-central-1" => %{"description" => "EU (Frankfurt)"},
        "eu-west-1" => %{"description" => "EU (Ireland)"},
        "eu-west-2" => %{"description" => "EU (London)"},
        "eu-west-3" => %{"description" => "EU (Paris)"},
        "eu-north-1" => %{"description" => "EU (Stockholm)"},
        "eu-south-1" => %{"description" => "EU (Milan)"},
        "eu-south-2" => %{"description" => "EU (Spain)"},
        "me-south-1" => %{"description" => "Middle East (Bahrain)"},
        "sa-east-1" => %{"description" => "South America (Sao Paulo)"},
        "us-east-1" => %{"description" => "US East (N. Virginia)"},
        "us-east-2" => %{"description" => "US East (Ohio)"},
        "us-west-1" => %{"description" => "US West (N. California)"},
        "us-west-2" => %{"description" => "US West (Oregon)"}
      },
      "services" => %{
        "s3" => %{
          "endpoints" => %{
            "us-east-1" => %{},
            "us-east-2" => %{},
            "us-west-1" => %{},
            "us-west-2" => %{},
            "ap-northeast-1" => %{},
            "ap-northeast-2" => %{},
            "ap-southeast-1" => %{},
            "ap-southeast-2" => %{},
            "ap-south-1" => %{},
            "eu-central-1" => %{},
            "eu-west-1" => %{},
            "eu-west-2" => %{},
            "eu-west-3" => %{},
            "sa-east-1" => %{}
          }
        }
      }
    }
  ]
}
