name: Testes e Qualidade de Código

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15.7"
          otp-version: "26.0"

      - name: Restaurar cache de dependências
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Instalar dependências
        run: mix deps.get

      - name: Compilar projeto
        env:
          MIX_ENV: test
        run: mix compile --warnings-as-errors

      - name: Executar testes
        env:
          MIX_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/app_test
        run: |
          mix ecto.create
          mix ecto.migrate
          mix test --max-failures 1

      - name: Upload cobertura de testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cobertura-testes
          path: cover/
          retention-days: 30

  lint:
    name: Verificação de Qualidade
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15.7"
          otp-version: "26.0"

      - name: Restaurar cache de dependências
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Instalar dependências
        run: mix deps.get

      - name: Verificar formatação
        run: mix format --check-formatted

      - name: Executar Credo
        run: mix credo --strict

  security:
    name: Verificação de Segurança
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15.7"
          otp-version: "26.0"

      - name: Restaurar cache de dependências
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Instalar dependências
        run: mix deps.get

      - name: Verificar vulnerabilidades
        run: mix deps.audit
